device: cpu
batch_size: 32
epochs: 5
workers: 2
train_path: D:/VSC/chromosome-classification/data/train_samples
test_path: D:/VSC/chromosome-classification/data/train_samples
classes: 24
wandb_log: false
project_name: chromosome-classification
tags:
  - resnet50
project_config:
  epochs: 100
val_split: 0.2
model_name: resnet50
